aws_region = "us-east-1"
aws_account_id = "676609476616"
aws_profile = "terraform-Dev-user"
user_bucket = "user-content-bucket-fileuploader-2024"
lambda_function_name = "FileUploaderLambda"
lambda_runtime = "python3.8"
webapp_bucket = "file-uploader-service-app-fajmayor"
